theme: jekyll-theme-minimal
title: Fabian Gallardo
description: Portafolio de desarrollador web y derrallador de software python
author: Fabian Gallardo
author_url: https://github.com/FabianGallardo-coder
author_email: gallardofabianvcpz@gmail.com 
author_avatar: /assets/images/avatar.png
url: https://fabian-gallardo.github.io
